spring: 
  application:
    name: order-service
  rabbitmq:  
    host: 192.168.126.132
    port: 5672
    username: admin
    password: admin 
#server:
 # port: 8201
 
#eureka注册配置  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
feign:
  hystrix:
    enabled: true #启用断路器降级和熔断
    
management: #暴露监控端点
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#集群设置
---
spring:
  profiles: order1
server:
  port: 8201
  
---
spring:
  profiles: order2
server:
  port: 8202